name: rec-${{ github.repository }}

on:
  workflow_run:
    workflows: ["OP-Master"]
    types: [completed]

jobs:
  rec_ok:
    runs-on: ubuntu-latest
    steps:
      - name: REC empfängt ROOT Kern-ID
        run: echo "REC: ROOT Kern-ID empfangen – Modul = ${{ github.repository }}"
