# root configuration (neutral, non-action)
meta:
  version: 1.0
  revision: 0001
  type: rec-root

load:
  set: "SET/set.yml"
  rec: "REC/rec.yml"
  wrt: "WRT/wrt.yml"

flags:
  safe: true
  github_ignore: true
  mode: minimal
